import boxingPic from "../public/assets/boxingCoachLists/boxingCoach.webp";
import boxingPic from "../public/assets/boxingCoachLists/boxingCoach2.webp";
import boxingPic from "../public/assets/boxingCoachLists/boxingCoach3.webp";
import kickBoxingCoach from "../public/kickBoxingCoachLists/kickBoxer.png";
import kickBoxingCoach2 from "../public/kickBoxingCoachLists/kickBoxer2.jpg";
import kickBoxingCoach3 from "../public/kickBoxingCoachLists/kickBoxer3.jpg";
import heavylifting from "../public/assets/heavylifting/heavyLifting1.jpg";
import heavylifting from "../public/assets/heavylifting/heavyLifting2.jpg";
import heavylifting from "../public/assets/heavylifting/heavyLifting3.jpg";
